# Generated by Django 5.0.2 on 2024-09-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_notices_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imgNoticias/'),
        ),
    ]
