# Generated by Django 5.0.1 on 2024-09-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_notices_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='content',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='notices',
            name='subject',
            field=models.CharField(max_length=20),
        ),
    ]
