# Generated by Django 5.1.1 on 2024-10-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_horario_remove_materia_horario_de_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('titulo', models.CharField(max_length=30)),
                ('contexto', models.CharField(max_length=20)),
                ('responsavel', models.CharField(max_length=20)),
            ],
        ),
    ]
