# Generated by Django 5.1.1 on 2024-10-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_recados'),
    ]

    operations = [
        migrations.AddField(
            model_name='recados',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imgRecados/'),
        ),
    ]
