# Generated by Django 5.1.1 on 2024-10-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_recados_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='horario_de_inicio',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='horario_de_termino',
            field=models.TimeField(null=True),
        ),
    ]
